repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version (keep in sync with the version in pyproject.toml)
  rev: v0.9.4
  hooks:
    # Run the linter first, as fixing will change files that need to be
    # formatted after
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      # This is run after the linter, so it can fix any issues that the linter
      # found.
      args: [ --fix-only ]