# Version of the specification language/format, to manage future changes
spec_version = "1.0"
# Version of this particular benchmark suite, to manage any important changes
suite_version = "0.1"
# Unique identifier for this benchmark suite
id = "compilation_benchmarks_unoptimized"
# Human readable description
description = "Base compilation benchmarks with pre-compilation quantum circuit unoptimization applied"

# --------- Unoptimization (Elementary Recipe) ----------
[unoptimization]
enabled = true
iterations = 1
strategy = "concatenated"     # or "random"
decomposition_method = "default" # one of: default, kak, basis
optimization_level = 3
# Optional: fix randomness for reproducibility
seed = 42

# --------- Compilers ----------
[[compilers]]
id = "ucc"
[[compilers]]
id = "pytket-peep"
[[compilers]]
id = "qiskit-default"
[[compilers]]
id = "cirq"
[[compilers]]
id = "pyqpanda3"

# --------- Benchmarks ----------

[[benchmarks]]
id = "qaoa"
description = "Quantum Approximate Optimization Algorithm of Barabási–Albert graph"
qasm_file = "circuits/benchpress/qaoa_barabasi_albert_N100_3reps_basis_rz_rx_ry_cx.qasm"

[[benchmarks]]
id = "qv"
description = "Quantum Volume"
qasm_file = "circuits/benchpress/qv_N100_12345_basis_rz_rx_ry_cx.qasm"

[[benchmarks]]
id = "qft"
description = "Quantum Fourier Transform"
qasm_file = "circuits/benchpress/qft_N100_basis_rz_rx_ry_cx.qasm"

[[benchmarks]]
id="square_heisenberg"
description = "Heisenberg spin model on square lattice"
qasm_file = "circuits/benchpress/square_heisenberg_N100_basis_rz_rx_ry_cx.qasm"

[[benchmarks]]
id="prep_select"
description = "Prepare and grover select all 1s state"
qasm_file = "circuits/ucc/prep_select_N25_ghz_basis_rz_rx_ry_h_cx.qasm"

[[benchmarks]]
id="qcnn"
description="Quantum Convolutional Neural Network"
qasm_file="circuits/ucc/qcnn_N100_7layers_basis_rz_rx_ry_h_cx.qasm"
