# Version of the specification language/format, to manage future changes
spec_version = "1.0"
# Version of this particular benchmark suite, to manage any important changes
suite_version = "0.1"
# Unique identifier for this benchmark suite
id = "compilation_benchmarks_unoptimized"
# Human readable description
description = "Benchmark circuits with the elementary unoptimization recipe applied offline"

# --------- Compilers ----------
[[compilers]]
id = "ucc"
[[compilers]]
id = "pytket-peep"
[[compilers]]
id = "qiskit-default"
[[compilers]]
id = "cirq"
[[compilers]]
id = "pyqpanda3"

# --------- Benchmarks ----------

[[benchmarks]]
id = "qaoa"
description = "Quantum Approximate Optimization Algorithm of Barabási–Albert graph"
qasm_file = "circuits/unoptimized/qaoa_barabasi_albert_N100_3reps_unopt.qasm"

[[benchmarks]]
id = "qv"
description = "Quantum Volume"
qasm_file = "circuits/unoptimized/qv_N100_12345_unopt.qasm"

[[benchmarks]]
id = "qft"
description = "Quantum Fourier Transform"
qasm_file = "circuits/unoptimized/qft_N100_unopt.qasm"

[[benchmarks]]
id = "square_heisenberg"
description = "Heisenberg spin model on square lattice"
qasm_file = "circuits/unoptimized/square_heisenberg_N100_unopt.qasm"

[[benchmarks]]
id = "prep_select"
description = "Prepare and grover select all 1s state"
qasm_file = "circuits/unoptimized/prep_select_N25_ghz_unopt.qasm"

[[benchmarks]]
id = "qcnn"
description = "Quantum Convolutional Neural Network"
qasm_file = "circuits/unoptimized/qcnn_N100_7layers_unopt.qasm"
